### PR TITLE
Readme Update (Main)

### PR DESCRIPTION
**Pull request by binarypheonix**
Updated the main meta_resoure README file with Introduction, Code of Conduct, How to, Guidelines, and other sections.

### CODE REVIEW

**Comment by rishistyping** [comment]
Looks great thanks @binarypheonix, will update w/ minor changes later.

**Comment by rishistyping** [comment]
https://github.com/matiassingers/awesome-readme @VikramxD

**Comment by VikramxD** [comment]
https://tom.preston-werner.com/2010/08/23/readme-driven-development.html @EXYNOS-999 @binarypheonix

**Comment by binarypheonix** [comment]
There's no rush, we need to also get the website up and rolling and update the README as we go

**Comment by rishistyping** [comment]
Yeah I'd love to put some hustle on everything including the research project, thats all.

**Pull request merged**
