### PR TITLE
Airtable Main Database View

### PR DESCRIPTION
**Pull request by binarypheonix**
Added the resource hyperlinks from the main Airtable database (after a lot of cleaning) to the meta_resource repo in the form of a list (as opposed to tables, since a lot of resources had missing fields) to facilitate the accessibility of these resources, along with links to the main database as well as the submission form.

### CODE REVIEW

**Comment by rishistyping** [comment]
Can we have a preview of the base itself in the README rather than listing a subset of the links + link to the actual base.

**Comment by rishistyping** [comment]
Test preview code.
`<iframe class="airtable-embed" src="https://airtable.com/embed/shrDN5mYU3dExG5x8?backgroundColor=teal&layout=card" frameborder="0" onmousewheel="" width="100%" height="533" style="background: transparent; border: 1px solid #ccc;"></iframe>`

**Comment by rishistyping** [comment]
Published preview: https://airtable.com/shrbwIwvU4YP6XwJU

**Comment by binarypheonix** [comment]
The link doesn't work in the iframe tag for some reason.

**Comment by Agrover112** [comment]
@EXYNOS-999  @binarypheonix  Maybe instead one could insert a GIF of the airtable Main View?
Like see the Pytorch Lightning repo , which has small looping GIF

**Comment by binarypheonix** [comment]
No the iframe is a good option but the preview isn't actually embedding the table, that's what I've encountered @EXYNOS-999

**Comment by rishistyping** [comment]
Cool updating preview.

**Pull request merged**
